spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/reseat
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=dev-only-secret-key-please-change-in-real-deployment-32bytes+
jwt.expiration-millis=1800000
jwt.refresh-expiration-millis=604800000

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

email.verification.code-ttl-seconds=300
email.verification.verified-ttl-seconds=1800
