### 값검
POST http://localhost:8083/api/tickets/hold/validation
Content-Type: application/json

{
  "ticketId": 34,
  "userId": 1,
  "price": 150000,
  "holdKey": "overtimekk"
}

### 공연상세 > 구간조회
POST http://localhost:8083/api/tickets/select/seat
Content-Type: application/json

{
  "performanceId": 3,
  "sessionNum" : 2,
  "zone" : "VIP"
}

### 좌석 점유 요청
PUT http://localhost:8083/api/tickets/status/hold
Content-Type: application/json
X-User-Id: 1

{
  "ticketId": 991,
  "orderType": "GENERAL"
}