spring.application.name=performance-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/reseat?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_0900_ai_ci&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

logging.level.root=info

order-service.url=http://localhost:8082

# 초기 데이터 적재 시, 주석 비활성화
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

# S3 설정
cloud.aws.region=ap-northeast-2
cloud.aws.s3.bucket=team01-reseat-bucket
cloud.aws.s3.image-prefix=image/

# user-service JWT 설정
jwt.secret=dev-only-secret-key-please-change-in-real-deployment-32bytes+
jwt.expiration-millis=1800000
jwt.refresh-expiration-millis=604800000